export const badwords = [
	"4r5e",
	"5h1t",
	"5hit",
	"a55",
	"anal",
	"anus",
	"ar5e",
	"arrse",
	"arse",
	"ass",
	"ass-fucker",
	"asses",
	"assfucker",
	"assfukka",
	"asshole",
	"assholes",
	"asswhole",
	"a_s_s",
	"b!tch",
	"b00bs",
	"b17ch",
	"b1tch",
	"ballbag",
	"balls",
	"ballsack",
	"bastard",
	"beastial",
	"beastiality",
	"bellend",
	"bestial",
	"bestiality",
	"bi+ch",
	"biatch",
	"bitch",
	"bitcher",
	"bitchers",
	"bitches",
	"bitchin",
	"bitching",
	"bloody",
	"blow job",
	"blowjob",
	"blowjobs",
	"boiolas",
	"bollock",
	"bollok",
	"boner",
	"boob",
	"boobs",
	"booobs",
	"boooobs",
	"booooobs",
	"booooooobs",
	"breasts",
	"buceta",
	"bugger",
	"bum",
	"bunny fucker",
	"butt",
	"butthole",
	"buttmuch",
	"buttplug",
	"c0ck",
	"c0cksucker",
	"carpet muncher",
	"cawk",
	"chink",
	"cipa",
	"cl1t",
	"clit",
	"clitoris",
	"clits",
	"cnut",
	"cock",
	"cock-sucker",
	"cockface",
	"cockhead",
	"cockmunch",
	"cockmuncher",
	"cocks",
	"cocksuck",
	"cocksucked",
	"cocksucker",
	"cocksucking",
	"cocksucks",
	"cocksuka",
	"cocksukka",
	"cok",
	"cokmuncher",
	"coksucka",
	"coon",
	"cox",
	"crap",
	"cum",
	"cummer",
	"cumming",
	"cums",
	"cumshot",
	"cunilingus",
	"cunillingus",
	"cunnilingus",
	"cunt",
	"cuntlick",
	"cuntlicker",
	"cuntlicking",
	"cunts",
	"cyalis",
	"cyberfuc",
	"cyberfuck",
	"cyberfucked",
	"cyberfucker",
	"cyberfuckers",
	"cyberfucking",
	"d1ck",
	"damn",
	"dick",
	"dickhead",
	"dildo",
	"dildos",
	"dink",
	"dinks",
	"dirsa",
	"dlck",
	"dog-fucker",
	"doggin",
	"dogging",
	"donkeyribber",
	"doosh",
	"duche",
	"dyke",
	"ejaculate",
	"ejaculated",
	"ejaculates",
	"ejaculating",
	"ejaculatings",
	"ejaculation",
	"ejakulate",
	"f u c k",
	"f u c k e r",
	"f4nny",
	"fag",
	"fagging",
	"faggitt",
	"faggot",
	"faggs",
	"fagot",
	"fagots",
	"fags",
	"fanny",
	"fannyflaps",
	"fannyfucker",
	"fanyy",
	"fatass",
	"fcuk",
	"fcuker",
	"fcuking",
	"feck",
	"fecker",
	"felching",
	"fellate",
	"fellatio",
	"fingerfuck",
	"fingerfucked",
	"fingerfucker",
	"fingerfuckers",
	"fingerfucking",
	"fingerfucks",
	"fistfuck",
	"fistfucked",
	"fistfucker",
	"fistfuckers",
	"fistfucking",
	"fistfuckings",
	"fistfucks",
	"flange",
	"fook",
	"fooker",
	"fuck",
	"fucka",
	"fucked",
	"fucker",
	"fuckers",
	"fuckhead",
	"fuckheads",
	"fuckin",
	"fucking",
	"fuckings",
	"fuckingshitmotherfucker",
	"fuckme",
	"fucks",
	"fuckwhit",
	"fuckwit",
	"fudge packer",
	"fudgepacker",
	"fuk",
	"fuker",
	"fukker",
	"fukkin",
	"fuks",
	"fukwhit",
	"fukwit",
	"fux",
	"fux0r",
	"f_u_c_k",
	"gangbang",
	"gangbanged",
	"gangbangs",
	"gaylord",
	"gaysex",
	"goatse",
	"God",
	"god-dam",
	"god-damned",
	"goddamn",
	"goddamned",
	"hardcoresex",
	"hell",
	"heshe",
	"hoar",
	"hoare",
	"hoer",
	"homo",
	"hore",
	"horniest",
	"horny",
	"hotsex",
	"jack-off",
	"jackoff",
	"jap",
	"jerk-off",
	"jism",
	"jiz",
	"jizm",
	"jizz",
	"kawk",
	"knob",
	"knobead",
	"knobed",
	"knobend",
	"knobhead",
	"knobjocky",
	"knobjokey",
	"kock",
	"kondum",
	"kondums",
	"kum",
	"kummer",
	"kumming",
	"kums",
	"kunilingus",
	"l3i+ch",
	"l3itch",
	"labia",
	"lust",
	"lusting",
	"m0f0",
	"m0fo",
	"m45terbate",
	"ma5terb8",
	"ma5terbate",
	"masochist",
	"master-bate",
	"masterb8",
	"masterbat*",
	"masterbat3",
	"masterbate",
	"masterbation",
	"masterbations",
	"masturbate",
	"mo-fo",
	"mof0",
	"mofo",
	"mothafuck",
	"mothafucka",
	"mothafuckas",
	"mothafuckaz",
	"mothafucked",
	"mothafucker",
	"mothafuckers",
	"mothafuckin",
	"mothafucking",
	"mothafuckings",
	"mothafucks",
	"mother fucker",
	"motherfuck",
	"motherfucked",
	"motherfucker",
	"motherfuckers",
	"motherfuckin",
	"motherfucking",
	"motherfuckings",
	"motherfuckka",
	"motherfucks",
	"muff",
	"mutha",
	"muthafecker",
	"muthafuckker",
	"muther",
	"mutherfucker",
	"n1gga",
	"n1gger",
	"nazi",
	"nigg3r",
	"nigg4h",
	"nigga",
	"niggah",
	"niggas",
	"niggaz",
	"nigger",
	"niggers",
	"nob",
	"nob jokey",
	"nobhead",
	"nobjocky",
	"nobjokey",
	"numbnuts",
	"nutsack",
	"orgasim",
	"orgasims",
	"orgasm",
	"orgasms",
	"p0rn",
	"pawn",
	"pecker",
	"penis",
	"penisfucker",
	"phonesex",
	"phuck",
	"phuk",
	"phuked",
	"phuking",
	"phukked",
	"phukking",
	"phuks",
	"phuq",
	"pigfucker",
	"pimpis",
	"piss",
	"pissed",
	"pisser",
	"pissers",
	"pisses",
	"pissflaps",
	"pissin",
	"pissing",
	"pissoff",
	"poop",
	"porn",
	"porno",
	"pornography",
	"pornos",
	"prick",
	"pricks",
	"pron",
	"pube",
	"pusse",
	"pussi",
	"pussies",
	"pussy",
	"pussys",
	"rectum",
	"retard",
	"rimjaw",
	"rimming",
	"s hit",
	"s.o.b.",
	"sadist",
	"schlong",
	"screwing",
	"scroat",
	"scrote",
	"scrotum",
	"semen",
	"sex",
	"sh!+",
	"sh!t",
	"sh1t",
	"shag",
	"shagger",
	"shaggin",
	"shagging",
	"shemale",
	"shi+",
	"shit",
	"shitdick",
	"shite",
	"shited",
	"shitey",
	"shitfuck",
	"shitfull",
	"shithead",
	"shiting",
	"shitings",
	"shits",
	"shitted",
	"shitter",
	"shitters",
	"shitting",
	"shittings",
	"shitty",
	"skank",
	"slut",
	"sluts",
	"smegma",
	"smut",
	"snatch",
	"son-of-a-bitch",
	"spac",
	"spunk",
	"s_h_i_t",
	"t1tt1e5",
	"t1tties",
	"teets",
	"teez",
	"testical",
	"testicle",
	"tit",
	"titfuck",
	"tits",
	"titt",
	"tittie5",
	"tittiefucker",
	"titties",
	"tittyfuck",
	"tittywank",
	"titwank",
	"tosser",
	"turd",
	"tw4t",
	"twat",
	"twathead",
	"twatty",
	"twunt",
	"twunter",
	"v14gra",
	"v1gra",
	"vagina",
	"viagra",
	"vulva",
	"w00se",
	"wang",
	"wank",
	"wanker",
	"wanky",
	"whoar",
	"whore",
	"willies",
	"willy",
	"xrated",
	"xxx",
];

export const interestCategories = [
	{
		id: "interest-business",
		name: "Business",
	},
	{
		id: "interest-relationships",
		name: "Family & Relationships",
	},
	{
		id: "interest-sport-wellness",
		name: "Sport & Wellness",
	},
	{
		id: "interest-food-drink",
		name: "Food & Drink",
	},
	{
		id: "interest-hobbies-activities",
		name: "Hobbies and activities",
	},
	{
		id: "interest-entertainment",
		name: "Entertainment",
	},
	{
		id: "interest-political-social",
		name: "Political & Social",
	},
	{
		id: "interest-pets",
		name: "Pets",
	},
] as const;

export const interests: {
	name: string;
	interestCategoryId: typeof interestCategories[number]["id"];
}[] = [
	{
		interestCategoryId: "interest-business",
		name: "Advertising",
	},
	{
		name: "Banking",
		interestCategoryId: "interest-business",
	},
	{
		name: "Business",
		interestCategoryId: "interest-business",
	},
	{
		name: "Design",
		interestCategoryId: "interest-business",
	},
	{
		name: "Digital marketing",
		interestCategoryId: "interest-business",
	},
	{
		name: "Entrepreneurship",
		interestCategoryId: "interest-business",
	},
	{
		name: "Finance",
		interestCategoryId: "interest-business",
	},
	{
		name: "Graphic design",
		interestCategoryId: "interest-business",
	},
	{
		name: "Insurance",
		interestCategoryId: "interest-business",
	},
	{
		name: "Investment",
		interestCategoryId: "interest-business",
	},
	{
		name: "Management",
		interestCategoryId: "interest-business",
	},
	{
		name: "Marketing",
		interestCategoryId: "interest-business",
	},
	{
		name: "Property & Real Estate",
		interestCategoryId: "interest-business",
	},
	{
		name: "Recruitment",
		interestCategoryId: "interest-business",
	},
	{
		name: "Sales",
		interestCategoryId: "interest-business",
	},
	{
		name: "Search engine optimization",
		interestCategoryId: "interest-business",
	},
	{
		name: "Small business",
		interestCategoryId: "interest-business",
	},
	{
		name: "Social media",
		interestCategoryId: "interest-business",
	},
	{
		name: "Technology",
		interestCategoryId: "interest-business",
	},
	{
		name: "Web design",
		interestCategoryId: "interest-business",
	},
	{
		name: "Dating",
		interestCategoryId: "interest-relationships",
	},
	{
		name: "Divorce",
		interestCategoryId: "interest-relationships",
	},
	{
		name: "Family",
		interestCategoryId: "interest-relationships",
	},
	{
		name: "Friendship",
		interestCategoryId: "interest-relationships",
	},
	{
		name: "Happily Single",
		interestCategoryId: "interest-relationships",
	},
	{
		name: "New Parent",
		interestCategoryId: "interest-relationships",
	},
	{
		name: "Parenting",
		interestCategoryId: "interest-relationships",
	},
	{
		name: "Single Dads",
		interestCategoryId: "interest-relationships",
	},
	{
		name: "Single Mums",
		interestCategoryId: "interest-relationships",
	},
	{
		name: "Weddings",
		interestCategoryId: "interest-relationships",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "American Football",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Athletics",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Badminton",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Baseball",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Basketball",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Cricket",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Darts",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Equestrian",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Fishing",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Football",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Gmnastics",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Gym",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Hiking",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Hockey",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Meditation",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Pilates",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Pool",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Rugby",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Running",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Skating",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Skiing",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Snooker",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Spin",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Swimming",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Table Tennis",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Tennis",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Volleyball",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Walking",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Weight training",
	},
	{
		interestCategoryId: "interest-sport-wellness",
		name: "Yoga",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Baking",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "BBQ",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Beer",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Chinese food",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Cocktails",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Coffee",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Greek food",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Indian food",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Italian food",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Japanese food",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Mexican food",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Middle Eastern food",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Pizza",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Real Ale",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Seafood",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Spanish food",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Tea",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Thai food",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Veganism",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Vegetarianism",
	},
	{
		interestCategoryId: "interest-food-drink",
		name: "Wine",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Acting",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Beauty",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Bird Watching",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Boats",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Book clubs",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Cars",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Collecting",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Comics",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Cooking",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Crafts",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Dance",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Drums",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Fashion",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Gardening",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Guitar",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Karaoke",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Literature",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Non-fiction books",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Painting",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Photography",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Podcasts",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Pottery",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Romance novels",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Sculpture",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Self-help",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Shopping",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Singing",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Travelling",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Wine tasting",
	},
	{
		interestCategoryId: "interest-hobbies-activities",
		name: "Writing",
	},
	{ interestCategoryId: "interest-entertainment", name: "Ballet" },
	{
		interestCategoryId: "interest-entertainment",
		name: "Bars",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Blues music",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Card games",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Classical music",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Concerts",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Country music",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Dance music",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Gambling",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Gaming",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Heavy metal music",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Hip hop music",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Jazz music",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Movies",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Music festivals",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Musical Theatre",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Nightclubs",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Parties",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Plays",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Pop music",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Rhythm and blues music",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Rock music",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Soul music",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Theatre",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "TV Shows",
	},
	{
		interestCategoryId: "interest-entertainment",
		name: "Word games",
	},
	{
		interestCategoryId: "interest-political-social",
		name: "Charity",
	},
	{
		interestCategoryId: "interest-political-social",
		name: "Community issues",
	},
	{
		interestCategoryId: "interest-political-social",
		name: "Environmentalism",
	},
	{
		interestCategoryId: "interest-political-social",
		name: "Law",
	},
	{
		interestCategoryId: "interest-political-social",
		name: "Politics",
	},
	{
		interestCategoryId: "interest-political-social",
		name: "Religion",
	},
	{
		interestCategoryId: "interest-pets",
		name: "Birds",
	},
	{
		interestCategoryId: "interest-pets",
		name: "Cats",
	},
	{
		interestCategoryId: "interest-pets",
		name: "Dogs",
	},
	{
		interestCategoryId: "interest-pets",
		name: "Fish",
	},
	{
		interestCategoryId: "interest-pets",
		name: "Horses",
	},
	{
		interestCategoryId: "interest-pets",
		name: "Rabbits",
	},
	{
		interestCategoryId: "interest-pets",
		name: "Reptiles",
	},
];
